# Site settings
title: Aristeides Stathopoulos
email: aristath@gmail.com
description: > # WordPress developer & themer
 focussed on UX, minimal design and making life simpler for others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aristeides.com" # the base hostname & protocol for your site
enable_retina: false
permalink: /blog/:title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<form action="https://www.paypal.com/cgi-bin/webscr" method="post"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="EXD2PDDWG7TJ8"><input type="submit" class="btn btn-alert btn-lg" name="submit" alt="PayPal - The safer, easier way to pay online!" value="I LOVE YOU, DONORS"></form>'
footer_links:
    About: ['About', '/about']


# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
