# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ari Stathopoulos"
description: > # this means to ignore newlines until "email:"
   WordPress Developer, Human.

email: aristath@gmail.com
#blog logo
logo: "/assets/images/aristath.png"
# blog cover
cover: "/assets/article_images/michael-benz-189972-unsplash.jpg"

name: 'Ari Stathopoulos'
author: 'Ari Stathopoulos'
author_image: "https://en.gravatar.com/userimage/4563555/80f13c810d16fa4c4817805648734eec.jpg?size=200"

paginate:	10

url: "https://aristath.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@aristath'

#fill in disqus shortname to use disqus
disqus: aristeides

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/aristath
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

# - icon:	facebook
#   url:	https://facebook.com/aristath
#   desc: Connect with me facebook
#   share_url: https://www.facebook.com/sharer.php
#   share_title: ?t=
#   share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/aristath
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

# - icon:	google-plus
#   url:	https://google.com/+AristeidesStathopoulos
#   desc:	Add me on google+
#   share_url:
#   share_title:
#   share_link:
