basic_settings:
  site_title: Ari Stathopoulos
  site_tagline: WordPress Developer, Accessibility & Sustainability evangelist, Human.
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Posts'
      url: '/'
    # - title: 'Projects'
    #   url: '/projects/'
    - title: 'About'
      url: '/about'
    # - title: 'Contact'
    #   url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/aristath@gmail.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/aristath'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/aristath'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#000'
  text_medium_color: '#222'
  text_light_color: '#666'
  accent_color: '#000'
  border_color: '#dddddd'
  overlay_background_color: '#000'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed:
  # font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Muli:400,400i,600" rel="stylesheet">'
  title_font: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif'
  body_font: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 2rem
    medium_size: 2rem
    large_size: 2rem
    weight: 900
    letter_spacing: 0
  site_tagline:
    small_size: .8rem
    medium_size: 1rem
    large_size: 1.2rem
    weight: 100
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 3rem
    medium_size: 1.5rem
    large_size: 2rem
    weight: 200
    letter_spacing: 0
  h1:
    small_size: 4.209rem
    medium_size: 4.209rem
    large_size: 4.209rem
    weight: 900
    letter_spacing: 0
    line_height: 1.5
  h2:
    small_size: 3.157rem
    medium_size: 3.157rem
    large_size: 3.157rem
    weight: 900
    letter_spacing: 0
    line_height: 1.5
  h3:
    small_size: 2.369rem
    medium_size: 2.369rem
    large_size: 2.369rem
    weight: 600
    letter_spacing: 0
    line_height: 1.3
  h4:
    small_size: 1.777rem
    medium_size: 1.777rem
    large_size: 1.777rem
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 1.333rem
    medium_size: 1.333rem
    large_size: 1.333rem
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 1rem
    medium_size: 1rem
    large_size: 1rem
    weight: 600
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 1rem
    medium_size: 1rem
    large_size: 1rem
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 1.75rem
    medium_size: 1.75rem
    large_size: 1.75rem
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""